[project]
name = "o1-replication"
version = "0.1.0"
description = "replication of o1"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "matplotlib>=3.10.0",
    "openai>=1.59.7",
    "tqdm>=4.67.1",
    "transformers>=4.48.0",
    "vllm==0.6.3",
]
